---
title: "r_from_gadinho_to_fuderoso"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R: de gadinho até fuderoso !
https://medium.com/data-hackers/python-from-zero-to-sidekick-eb31dc8d1fa8


### Comentário

```{r}
#Comentário de uma linha


# Comentário de várias linhas
# Comentário de várias linhas
# Comentário de várias linhas


```
  
### Imprimindo valores

Para imprimir valores no R é possível usar 
```{r}
print("Olar python users")
cat("Olar python users")
```


### Variáveis

```{r}
#String
nome <- "Ellon"
sobrenome <- "Musk"

#concatenando string
paste(nome , sobrenome)
print("--------------------")

#númerica
idade <- 10
idade 
print("--------------------")

#float
altura <- 1.70
altura
print("--------------------")

#coleção
empresas <- c( "spaceX" ,"openIA" )
empresas
print("--------------------")

#lista
lista <- list( nome,idade,altura,empresas )
lista

cat(lista[0])
cat(lista[1])
print("--------------------")

lista <- list( nome=nome,idade=idade,altura=altura,empresas=empresas )
lista



#matriz
mdat <- matrix(
        c(1,2,3, 11,12,13), 
        nrow = 2, 
        ncol = 3)

mdat

#3
mdat[1,2]

```

###Operadores 

```{r}
1 + 2
```


